name: 生成股票组配置

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'topic/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'topic/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入内容
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 运行生成脚本
        run: |
          python3 scripts/generate_stock_group.py
          
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stockGroup.json
          
          # 检查是否有更改
          if git diff --staged --quiet; then
            echo "没有更改需要提交"
          else
            git commit -m "自动更新 stockGroup.json [skip ci]"
            git push
          fi
